### ISSUE TITLE
Where can I download articles now?

### ISSUE THREAD

**Issue by zuowanbushiwo** [ffxiong/stsubnet#3]
Hi @feifeixiong  @ffxiong 
    I am very interested in this article(Deep Subband Network for Joint Suppression of Echo, Noise and Reverberation in Real-Time Fullband Speech Communication), where can I download it? Can the source code be opened? Thanks!

**Comment by feifeixiong** [comment]
Hi, 

Currently the paper is not yet uploaded for public download until the ICASSP conference begins at 04 June. If you'd like to have the initial version, please visit https://www.researchgate.net/publication/368665735_Deep_Subband_Network_for_Joint_Suppression_of_Echo_Noise_and_Reverberation_in_Real-Time_Fullband_Speech_Communication

Regarding the source code, since the work is with Alibaba (commercial) ，it will be difficult to open the source code, sorry for this! If you'd like to repeat our work, any questions are welcome.

**Comment by zuowanbushiwo** [comment]
好的，非常感谢！
请问 你们训练集/测试集 中得echo 语音，都是使用AEC challenge中的吗？
我看你们文章中有这句话：
 the echo signal, we use all the synthetic echo signals and real far-end single   talk recordings provided by ICASSP 2022 AEC challenge  
但是看到后面又有这句话：
  We follow the typical nonlinear distortion simulation from [32, 33], including amplifier clipping, loudspeaker dynamic distortion, and asymmetric loudspeaker distortion.  
如果你们使用AEC 中的echo 语音，为什么还要仿真非线性失真，这个是产生echo信号步骤？

能否开源部分关于数据扩增的部分实现，我主要是对这部分非常迷惑，看了AEC challenge中没有看到相关的数据扩增的脚本。
谢谢！

**Comment by feifeixiong** [comment]
We follow the typical nonlinear distortion simulation from [32, 33], including amplifier clipping, loudspeaker dynamic distortion, and asymmetric loudspeaker distortion.

这个是我只用了 AEC challenge far-end （只是远端信号）数据，并没有用 AEC challenge 训练集里面已经生成好的 echo signal 

数据扩增部分的code开放也需要申请，这个不好意思，可能没这么快，不过可以看下paper里面的 signal model ，我基本上都是按照公式来仿真的数据

**Comment by zuowanbushiwo** [comment]
你好，感谢回复。
你是用了三种数据集吗？
第一种是AEC challenge 中的 dataset/synthetic 中的部分数据集 ，这应该是一个完整是信号集包括了echo_signal，farend_speech，nearend_mic_signal，nearend_speech 
第二种是 AEC challenge 中的 dataset/real 种的  far-end single talk 部分， 这个是使用 `**_farend_singletalk_**_lpb.wav` 做farend_speech，使用 `**_farend_singletalk_**_mic.wav` 做 echo_signal， 再使用其它语音数据集(TIMIT) 和噪声集(noise-92) 按照SNR和SER 合成 nearend_speech 和  nearend_mic_signal 吗？
第三部分是AEC challenge  dataset 中 除了上面的两种情况的(好像也只有` **doubletalk_with_**_lpb.wav`)远端信号，自己合成echo signal，nearend_speech ，nearend_mic_signal ，这一步产生echo signal 信号的时候就需要上面的非线性失真的方法？
谢谢！

**Comment by feifeixiong** [comment]
第一种是AEC challenge 中的 dataset/synthetic 中的部分数据集 ，这个只用了 farend_speech， 其他都是我这边自己的数据仿真 
第二种是 AEC challenge 中的 dataset/real 这个都用了， 因为包含了 real RIRs 在里面 
其他都是仿真的了

**Comment by zuowanbushiwo** [comment]
你好，非常感谢您的回复，但是看到你的回复我更伤心了，没有比较强的信号处理基础看这部分很崩溃。
关于第一部分  dataset/synthetic  为什么只用了 farend_speech，没有用全套的？我听了几个这里面音频，感觉farend_speech就只是干净的语音？我看看到很多文章都是用这里面 echo_signal，farend_speech，nearend_mic_signal，nearend_speech 做训练，是这里面的echo signal 有问题吗？
关于第二部分  dataset/real   里面的 `**doubletalk_with_**_lpb.wav`  `**doubletalk_with_**_mic.wav`  也能用吗？这组合里面没办法获得 nearend_speech ，没办法计算loss？
谢谢！

**Comment by feifeixiong** [comment]
第一部分可控的就用，不可控的就不用，因为最后还是要得到 near-end speech 作为  target 

第二部分我只用了 far-end talk，意思是 far-end talk  和 echo 是 real 的， near-end 噪音和混响是 仿真的

**Comment by zuowanbushiwo** [comment]
好的， 理解了，还是期待你开源数据扩增部分，谢谢！
